[build]
  command = "pnpm build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# SPA rewrite: envia tudo para index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
